### ISSUE TITLE
How to Run this

### ISSUE THREAD

**Issue by yudis** [quasipedia/atc-ng#48]
I've tried to find (from any Readme or docs) to run this game.
Is there anyone can shed me some lights here...

Thank you

**Comment by quasipedia** [comment]
Hi yudis!

Disclaimer first: the project hasn't been a priority of mine for months now, and the available version is to be considered "alpha". If there is interest in it, I'd be happy to finish it off: to date, the game is fully playable but it needs work to be enjoyable (the only scenario shipped with it is rather boring, the difficult progression could be better, etc...).

That said: the easiest way to try it out is to install the deb package that you can download from the [download link](https://github.com/quasipedia/atc-ng/downloads) here on GitHub. Installation should populate your menu also with the game entry. You should also install `python-yaml` and `pygame` on your system, if the installer fails to do it itself.

I assume you are already aware of the documentation/instructions available [here](http://quasipedia.github.com/atc-ng/).

If you try this out, I would love to receive some feedback! (especially stuff that doesn't work). You are welcome to drop me a line via mail if you prefer. My address is "quasipedia" (on gmail).
